review_version: 5.0
bookname: book
language: ja
booktitle: pandoc2reviewサンプル書籍
aut: ["武藤健志"]
date: 2020-12-31
history: [["2020-12-31"]]
debug: null
stylesheet: ["style.css"]
toclevel: 3
secnolevel: 2
toc: true
coverimage: cover.jpg
epubmaker:
  htmlext: xhtml
texstyle: ["reviewmacro"]
texdocumentclass: ["review-jsbook", "media=print,paper=a5"]
pdfmaker:
  colophon: true
contentdir: _refiles
