name: Pandoc
on: push

jobs:
  Pandoc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: r-lib/actions/setup-pandoc@v1
      with:
        pandoc-version: '2.11.3'
    - run: pandoc -v
