name: Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
   steps:
   - uses: actions/checkout@v2
   - name: Setup Ruby
     uses: ruby/setup-ruby@v1
     with:
       ruby-version: 2.7
   - name: build and test
     run: |
       gem install bundler --no-document
       bundle install --retry 3
       bundle exec ruby test/run_test.rb
