name: Test
on: [push]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        ruby: [2.7]
        # os: [ubuntu-latest macOS-latest]
        os: [ubuntu-latest]
   steps:
   - uses: actions/checkout@v2
# FIXME: Install pandoc
   - name: Setup Ruby
     uses: ruby/setup-ruby@v1
     with:
       ruby-version: ${{ matrix.ruby }}
   - name: build and test
     run: |
       gem install bundler --no-document
       bundle install --retry 3
       bundle exec ruby test/run_test.rb
